version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=my_database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
volumes:
  postgres_data:
    driver: local
