# Generated by Django 5.2.7 on 2025-10-28 22:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School_year',
            fields=[
                ('SchoolYearID', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(help_text="Año escolar: '2023-2024'", max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('SubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('TeacherID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(choices=[('Eso', 'Eso'), ('Bachillerato', 'Bachillerato'), ('IB', 'IB')], max_length=20)),
                ('Section', models.CharField(max_length=2)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.school_year')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('professor', 'professor'), ('student', 'student'), ('tutor', 'legal_tutor'), ('administrator', 'administrator')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('children', models.ManyToManyField(blank=True, related_name='tutors', to='mainapp.students')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.students')),
            ],
        ),
        migrations.CreateModel(
            name='Students_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.course', verbose_name='Sección de Curso Asignada')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.students')),
            ],
            options={
                'unique_together': {('student', 'course_section')},
            },
        ),
        migrations.CreateModel(
            name='Trimester',
            fields=[
                ('TrimesterID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')])),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.school_year')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_course_sections', models.ManyToManyField(to='mainapp.students_courses')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teachers')),
                ('trimester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.trimester')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('grade_type', models.CharField(choices=[('examen', 'examen'), ('parcial', 'parcial'), ('trimestral', 'trimestral'), ('final', 'final'), ('otros', 'otros')], max_length=15)),
                ('grade_type_number', models.PositiveIntegerField(blank=True, default=0)),
                ('comments', models.TextField(blank=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.school_year')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subjects')),
                ('trimester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.trimester')),
            ],
            options={
                'unique_together': {('student', 'subject', 'trimester', 'school_year', 'grade_type', 'grade_type_number')},
            },
        ),
        migrations.CreateModel(
            name='Ausencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(choices=[('Ausencia', 'Ausencia'), ('Retraso', 'Retraso')], max_length=20)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.school_year')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subjects')),
                ('trimester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.trimester')),
            ],
            options={
                'unique_together': {('student', 'subject', 'trimester', 'date_time')},
            },
        ),
    ]
