# Generated by Django 5.2.6 on 2025-10-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.CreateModel(
            name='Ausencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(choices=[('Ausencia', 'Ausencia'), ('Retraso', 'Retraso')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subjects')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.teachers')),
                ('trimester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.trimester')),
            ],
        ),
    ]
