# Generated by Django 5.2.16 on 2026-08-02 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_year',
            name='year',
            field=models.CharField(help_text="Format: '2023-2024'", max_length=9),
        ),
        migrations.AlterField(
            model_name='students_courses',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.course', verbose_name='Assigned Course Section'),
        ),
    ]
