# Generated by Django 5.2.7 on 2025-10-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_type_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('examen', 'examen'), ('parcial', 'parcial'), ('trimestral', 'trimestral'), ('final', 'final'), ('otros', 'otros')], max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'trimester', 'grade_type', 'grade_type_number')},
        ),
    ]
