# Generated by Django 5.2.6 on 2025-09-28 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_students_studentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(choices=[('Eso', 'Eso'), ('Bachillerato', 'Bachillerato'), ('IB', 'IB')], max_length=20)),
                ('Section', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('SubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('TeacherID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trimester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trimestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
    ]
