# Generated by Django 5.2.6 on 2025-10-02 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_grade_grade_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausencias',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
